#include "ui/EditorStyle.h"

#include <QApplication>
#include <QString>

namespace
{
QString BuildApplicationStyleSheet()
{
	return QStringLiteral(
		/* Base */
		"QWidget {"
		"  background-color: #252526;"
		"  color: #e0e0e0;"
		"  selection-background-color: #2c5d87;"
		"  selection-color: #ffffff;"
		"  font-size: 12px;"
		"}"

		/* Viewport (keep darker than panels) */
		"QWidget#RenderViewportWidget {"
		"  background-color: #101214;"
		"}"
		"QWidget#ViewportHostWidget {"
		"  background: transparent;"
		"  background-color: transparent;"
		"}"

		/* Main window / docks / dialogs */
		"QMainWindow {"
		"  background-color: #1e1e1e;"
		"}"
		"QDockWidget {"
		"  background-color: #252526;"
		"  color: #e0e0e0;"
		"  titlebar-close-icon: none;"
		"}"
		"QDockWidget::title {"
		"  background-color: #2d2d30;"
		"  color: #cccccc;"
		"  padding: 4px 6px;"
		"  text-align: left;"
		"}"
		"QTabBar::tab {"
		"  background-color: #2d2d30;"
		"  color: #9a9a9a;"
		"  padding: 5px 12px;"
		"  border: 1px solid #3f3f46;"
		"  border-bottom: none;"
		"  margin-right: 1px;"
		"}"
		"QTabBar::tab:selected {"
		"  background-color: #252526;"
		"  color: #f0f0f0;"
		"}"
		"QTabBar::tab:hover {"
		"  background-color: #3a3a3d;"
		"}"
		"QDialog {"
		"  background-color: #252526;"
		"}"

		/* Menu */
		"QMenuBar {"
		"  background-color: #2d2d30;"
		"  color: #e0e0e0;"
		"  border-bottom: 1px solid #3f3f46;"
		"}"
		"QMenuBar::item {"
		"  background: transparent;"
		"  padding: 4px 10px;"
		"}"
		"QMenuBar::item:selected {"
		"  background-color: #3e3e42;"
		"}"
		"QMenu {"
		"  background-color: #2d2d30;"
		"  color: #e0e0e0;"
		"  border: 1px solid #3f3f46;"
		"}"
		"QMenu::item:selected {"
		"  background-color: #2c5d87;"
		"}"

		/* Group box */
		"QGroupBox {"
		"  background-color: #252526;"
		"  color: #c8c8c8;"
		"  border: 1px solid #3f3f46;"
		"  border-radius: 2px;"
		"  margin-top: 10px;"
		"  padding-top: 8px;"
		"}"
		"QGroupBox::title {"
		"  subcontrol-origin: margin;"
		"  subcontrol-position: top left;"
		"  left: 8px;"
		"  padding: 0 4px;"
		"  color: #c8c8c8;"
		"}"

		/* Labels */
		"QLabel {"
		"  background: transparent;"
		"  color: #e0e0e0;"
		"}"
		"QLabel#PanelHeaderLabel {"
		"  font-weight: bold;"
		"  color: #f0f0f0;"
		"}"
		"QLabel#SecondaryLabel {"
		"  color: #9a9a9a;"
		"}"
		"QLabel#EditorStatusLabel {"
		"  color: #9a9a9a;"
		"  padding: 6px;"
		"  background-color: #2d2d30;"
		"  border: 1px solid #3f3f46;"
		"  border-radius: 2px;"
		"}"
		"QLabel#EditorStatusLabel[status=\"success\"] {"
		"  color: #6abf40;"
		"}"
		"QLabel#EditorStatusLabel[status=\"error\"] {"
		"  color: #e05252;"
		"}"
		"QLabel#EditorStatusLabel[status=\"normal\"] {"
		"  color: #9a9a9a;"
		"}"

		/* Text inputs (sunken) */
		"QLineEdit, QAbstractSpinBox, QDoubleSpinBox, QSpinBox {"
		"  background-color: #0a0a0a;"
		"  color: #e8e8e8;"
		"  border: 1px solid #3f3f46;"
		"  border-radius: 2px;"
		"  padding: 3px 6px;"
		"  min-height: 20px;"
		"}"
		"QLineEdit:focus, QAbstractSpinBox:focus, QDoubleSpinBox:focus, QSpinBox:focus {"
		"  border: 1px solid #4a78c8;"
		"}"
		"QLineEdit:disabled, QAbstractSpinBox:disabled {"
		"  background-color: #1a1a1a;"
		"  color: #6a6a6a;"
		"}"
		"QLineEdit::placeholder {"
		"  color: #6e6e6e;"
		"}"

		/* Spin box buttons */
		"QAbstractSpinBox::up-button, QAbstractSpinBox::down-button {"
		"  background-color: #2d2d30;"
		"  border: none;"
		"  width: 14px;"
		"}"
		"QAbstractSpinBox::up-button:hover, QAbstractSpinBox::down-button:hover {"
		"  background-color: #3e3e42;"
		"}"
		"QAbstractSpinBox::up-arrow, QAbstractSpinBox::down-arrow {"
		"  width: 8px;"
		"  height: 8px;"
		"}"

		/* Tree / list (Outliner) */
		"QTreeWidget, QTreeView, QListView {"
		"  background-color: #1b1b1c;"
		"  color: #d8d8d8;"
		"  border: 1px solid #3f3f46;"
		"  alternate-background-color: #232324;"
		"  outline: none;"
		"}"
		"QTreeWidget::item, QTreeView::item {"
		"  padding: 2px 0;"
		"}"
		"QTreeWidget::item:hover, QTreeView::item:hover {"
		"  background-color: #2a2d2e;"
		"}"
		"QTreeWidget::item:selected, QTreeView::item:selected {"
		"  background-color: #2c5d87;"
		"  color: #ffffff;"
		"}"

		/* Asset browser */
		"QListView#AssetBrowserGrid {"
		"  background-color: #252526;"
		"  border: 1px solid #3f3f46;"
		"}"
		"QLineEdit#AssetBrowserSearchEdit {"
		"  background-color: #1a1a1a;"
		"  border: 1px solid #3f3f46;"
		"  padding: 4px 6px;"
		"}"
		"QLineEdit#OutputLogSearchEdit {"
		"  background-color: #1a1a1a;"
		"  border: 1px solid #3f3f46;"
		"  padding: 4px 6px;"
		"}"
		"QTextEdit#OutputLogView {"
		"  background-color: #1e1e1e;"
		"  color: #d4d4d4;"
		"  border: 1px solid #3f3f46;"
		"  padding: 4px 6px;"
		"}"
		"QScrollArea#EditorScrollArea {"
		"  background-color: #252526;"
		"  border: none;"
		"}"
		"QHeaderView::section {"
		"  background-color: #2d2d30;"
		"  color: #9a9a9a;"
		"  padding: 4px 6px;"
		"  border: none;"
		"  border-right: 1px solid #3f3f46;"
		"  border-bottom: 1px solid #3f3f46;"
		"}"

		/* Buttons */
		"QPushButton {"
		"  background-color: #3e3e42;"
		"  color: #f0f0f0;"
		"  border: 1px solid #555555;"
		"  border-radius: 2px;"
		"  padding: 4px 12px;"
		"  min-height: 22px;"
		"}"
		"QPushButton:hover {"
		"  background-color: #4a4a50;"
		"  border-color: #6a6a70;"
		"}"
		"QPushButton:pressed {"
		"  background-color: #2d2d30;"
		"}"
		"QPushButton:disabled {"
		"  background-color: #2a2a2a;"
		"  color: #6a6a6a;"
		"  border-color: #3a3a3a;"
		"}"
		"QDialogButtonBox QPushButton {"
		"  min-width: 72px;"
		"}"

		/* Slider */
		"QSlider::groove:horizontal {"
		"  height: 4px;"
		"  background: #1a1a1a;"
		"  border: 1px solid #3f3f46;"
		"  border-radius: 2px;"
		"}"
		"QSlider::handle:horizontal {"
		"  width: 12px;"
		"  height: 12px;"
		"  margin: -5px 0;"
		"  background: #c8c8c8;"
		"  border: 1px solid #6a6a70;"
		"  border-radius: 6px;"
		"}"
		"QSlider::sub-page:horizontal {"
		"  background: #4a78c8;"
		"  border-radius: 2px;"
		"}"

		/* Scroll bars */
		"QScrollBar:vertical {"
		"  background: #1e1e1e;"
		"  width: 12px;"
		"  margin: 0;"
		"}"
		"QScrollBar::handle:vertical {"
		"  background: #424242;"
		"  min-height: 24px;"
		"  border-radius: 4px;"
		"}"
		"QScrollBar::handle:vertical:hover {"
		"  background: #4f4f4f;"
		"}"
		"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
		"  height: 0;"
		"}"
		"QScrollBar:horizontal {"
		"  background: #1e1e1e;"
		"  height: 12px;"
		"}"
		"QScrollBar::handle:horizontal {"
		"  background: #424242;"
		"  min-width: 24px;"
		"  border-radius: 4px;"
		"}"
		"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {"
		"  width: 0;"
		"}"

		/* Form layout spacing hint */
		"QFormLayout {"
		"  background: transparent;"
		"}"

		/* Camera speed overlay (viewport) */
		"QWidget#CameraSpeedControlRoot {"
		"  background: transparent;"
		"}"
		"QPushButton#CameraSpeedTrigger {"
		"  background: transparent;"
		"  border: none;"
		"  padding: 0px;"
		"}"
		"QFrame#CameraSpeedPopup {"
		"  background-color: rgba(45, 45, 48, 245);"
		"  color: #e0e0e0;"
		"  border: 1px solid #56565e;"
		"  border-radius: 4px;"
		"}"
		"QLabel#CameraSpeedSectionLabel {"
		"  color: #9a9a9a;"
		"  font-size: 11px;"
		"}"
		"QLabel#CameraSpeedValueLabel {"
		"  color: #e8e8e8;"
		"}"
		"QSlider#CameraSpeedSlider::groove:horizontal {"
		"  background: #1a1a1a;"
		"}"
		"QLineEdit#CameraSpeedScalarEdit {"
		"  background-color: #0a0a0a;"
		"}");
}
} // namespace

void EditorStyle::ApplyApplicationStyle(QApplication* InApplication)
{
	if (InApplication == nullptr)
	{
		return;
	}

	InApplication->setStyle(QStringLiteral("Fusion"));
	InApplication->setStyleSheet(BuildApplicationStyleSheet());
}
