# Embed MSVC / Windows SDK include and library paths in target build lines so Ninja
# builds work from plain shells without vcvars (ReflectionGenerator is often built alone).

function(_ost_resolve_windows_sdk_version OutVersion)
	set(_ResolvedVersion "")
	if(CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION)
		set(_ResolvedVersion "${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}")
	endif()

	if(_ResolvedVersion STREQUAL "" AND DEFINED ENV{WindowsSDKVersion})
		string(STRIP "$ENV{WindowsSDKVersion}" _EnvSdkVersion)
		string(REGEX REPLACE "\\\\$" "" _EnvSdkVersion "${_EnvSdkVersion}")
		if(_EnvSdkVersion MATCHES "^[0-9]+\\.[0-9]+")
			set(_ResolvedVersion "${_EnvSdkVersion}")
		endif()
	endif()

	if(_ResolvedVersion STREQUAL "")
		set(_KitIncludeRoot "C:/Program Files (x86)/Windows Kits/10/Include")
		if(NOT EXISTS "${_KitIncludeRoot}" AND DEFINED ENV{WindowsSdkDir})
			get_filename_component(_KitIncludeRoot "$ENV{WindowsSdkDir}/Include" ABSOLUTE)
		endif()

		if(EXISTS "${_KitIncludeRoot}")
			file(GLOB _SdkVersionCandidates RELATIVE "${_KitIncludeRoot}" "${_KitIncludeRoot}/*")
			foreach(_Candidate IN LISTS _SdkVersionCandidates)
				if(_Candidate MATCHES "^[0-9]+\\.[0-9]+" AND EXISTS "${_KitIncludeRoot}/${_Candidate}/ucrt")
					if(_ResolvedVersion STREQUAL "" OR _Candidate VERSION_GREATER _ResolvedVersion)
						set(_ResolvedVersion "${_Candidate}")
					endif()
				endif()
			endforeach()
		endif()
	endif()

	set("${OutVersion}" "${_ResolvedVersion}" PARENT_SCOPE)
endfunction()

function(_ost_resolve_windows_kit_root OutKitRoot)
	set(_KitRoot "C:/Program Files (x86)/Windows Kits/10")
	if(NOT EXISTS "${_KitRoot}" AND DEFINED ENV{WindowsSdkDir})
		get_filename_component(_KitRoot "$ENV{WindowsSdkDir}" ABSOLUTE)
	endif()
	set("${OutKitRoot}" "${_KitRoot}" PARENT_SCOPE)
endfunction()

function(ost_target_add_msvc_std_includes InTarget)
	if(NOT MSVC OR NOT TARGET "${InTarget}")
		return()
	endif()

	if(CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES)
		target_include_directories("${InTarget}" PRIVATE ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})
	endif()

	get_filename_component(_ClDir "${CMAKE_CXX_COMPILER}" DIRECTORY)
	get_filename_component(_MsvcToolsetRoot "${_ClDir}/../../.." ABSOLUTE)
	set(_MsvcIncludeDir "${_MsvcToolsetRoot}/include")
	if(EXISTS "${_MsvcIncludeDir}")
		target_include_directories("${InTarget}" PRIVATE "${_MsvcIncludeDir}")
	endif()

	_ost_resolve_windows_sdk_version(_SdkVersion)
	if(_SdkVersion STREQUAL "")
		message(WARNING "ost_target_add_msvc_std_includes: Windows SDK version not found for ${InTarget}.")
		return()
	endif()

	_ost_resolve_windows_kit_root(_WindowsKitRoot)
	if(NOT EXISTS "${_WindowsKitRoot}")
		message(WARNING "ost_target_add_msvc_std_includes: Windows Kits root not found for ${InTarget}.")
		return()
	endif()

	set(_SdkIncludeRoot "${_WindowsKitRoot}/Include/${_SdkVersion}")
	foreach(_SdkIncludeDir IN ITEMS ucrt shared um)
		set(_Candidate "${_SdkIncludeRoot}/${_SdkIncludeDir}")
		if(EXISTS "${_Candidate}")
			target_include_directories("${InTarget}" PRIVATE "${_Candidate}")
		endif()
	endforeach()
endfunction()

function(ost_target_add_msvc_std_libs InTarget)
	if(NOT MSVC OR NOT TARGET "${InTarget}")
		return()
	endif()

	if(CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES)
		target_link_directories("${InTarget}" PRIVATE ${CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES})
	endif()

	get_filename_component(_ClDir "${CMAKE_CXX_COMPILER}" DIRECTORY)
	get_filename_component(_MsvcToolsetRoot "${_ClDir}/../../.." ABSOLUTE)
	set(_MsvcLibDir "${_MsvcToolsetRoot}/lib/x64")
	if(EXISTS "${_MsvcLibDir}")
		target_link_directories("${InTarget}" PRIVATE "${_MsvcLibDir}")
	endif()

	_ost_resolve_windows_sdk_version(_SdkVersion)
	if(_SdkVersion STREQUAL "")
		message(WARNING "ost_target_add_msvc_std_libs: Windows SDK version not found for ${InTarget}.")
		return()
	endif()

	_ost_resolve_windows_kit_root(_WindowsKitRoot)
	if(NOT EXISTS "${_WindowsKitRoot}")
		message(WARNING "ost_target_add_msvc_std_libs: Windows Kits root not found for ${InTarget}.")
		return()
	endif()

	set(_SdkLibRoot "${_WindowsKitRoot}/Lib/${_SdkVersion}")
	foreach(_SdkLibDir IN ITEMS ucrt/x64 um/x64)
		set(_Candidate "${_SdkLibRoot}/${_SdkLibDir}")
		if(EXISTS "${_Candidate}")
			target_link_directories("${InTarget}" PRIVATE "${_Candidate}")
		endif()
	endforeach()
endfunction()

function(ost_target_add_msvc_std_paths InTarget)
	ost_target_add_msvc_std_includes("${InTarget}")
	ost_target_add_msvc_std_libs("${InTarget}")
endfunction()
