#include "CodeEmitter.h"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

namespace
{
std::string EscapeString(const std::string& InValue)
{
	std::string Result;
	Result.reserve(InValue.size());
	for (char Character : InValue)
	{
		if (Character == '\\' || Character == '"')
		{
			Result.push_back('\\');
		}
		Result.push_back(Character);
	}
	return Result;
}

bool WriteTextFile(const std::filesystem::path& InFilePath, const std::string& InContent, std::string* OutErrorMessage)
{
	std::error_code Ec;
	std::filesystem::create_directories(InFilePath.parent_path(), Ec);

	std::ofstream Stream(InFilePath, std::ios::binary | std::ios::trunc);
	if (!Stream.is_open())
	{
		if (OutErrorMessage != nullptr)
		{
			*OutErrorMessage = "Failed to write file: " + InFilePath.string();
		}
		return false;
	}

	Stream << InContent;
	return true;
}

std::string BuildFlagsInitializer(const std::vector<std::string>& InFlags)
{
	if (InFlags.empty())
	{
		return "{}";
	}

	std::ostringstream Builder;
	Builder << "{ ";
	for (std::size_t Index = 0; Index < InFlags.size(); ++Index)
	{
		if (Index > 0)
		{
			Builder << ", ";
		}
		Builder << '"' << EscapeString(InFlags[Index]) << '"';
	}
	Builder << " }";
	return Builder.str();
}
} // namespace

bool EmitReflectionGeneratedFiles(const FReflectionClassRecord& InClassRecord, const std::filesystem::path& InOutputDirectory, std::string* OutErrorMessage)
{
	const std::filesystem::path GeneratedHeaderPath = InOutputDirectory / (InClassRecord.ClassName + ".generated.h");
	const std::filesystem::path GeneratedSourcePath = InOutputDirectory / (InClassRecord.ClassName + ".gen.cpp");

	std::ostringstream HeaderBuilder;
	HeaderBuilder << "// Generated by ReflectionGenerator. Do not edit.\n";
	HeaderBuilder << "#pragma once\n\n";
	HeaderBuilder << "#define FID_" << InClassRecord.ClassName << "_GENERATED_BODY() \\\n";
	HeaderBuilder << "\tfriend struct Z_Construct_UClass_" << InClassRecord.ClassName << "_Statics;\n\n";
	HeaderBuilder << "#undef GENERATED_BODY\n";
	HeaderBuilder << "#define GENERATED_BODY() FID_" << InClassRecord.ClassName << "_GENERATED_BODY()\n\n";
	HeaderBuilder << "void RegisterGeneratedClass_" << InClassRecord.ClassName << "();\n";

	const std::string HeaderInclude =
		InClassRecord.HeaderIncludePath.empty() ? InClassRecord.HeaderPath.filename().string() : InClassRecord.HeaderIncludePath;

	std::ostringstream SourceBuilder;
	SourceBuilder << "// Generated by ReflectionGenerator. Do not edit.\n";
	SourceBuilder << "#include \"" << InClassRecord.ClassName << ".generated.h\"\n";
	SourceBuilder << "#include \"" << HeaderInclude << "\"\n";
	SourceBuilder << "#include \"reflection/GeneratedRegistration.h\"\n\n";
	SourceBuilder << "namespace\n";
	SourceBuilder << "{\n";
	SourceBuilder << "const std::vector<FGeneratedPropertyDesc> GGeneratedProperties_" << InClassRecord.ClassName << " = {\n";
	for (const FReflectionFieldRecord& FieldRecord : InClassRecord.Fields)
	{
		if (!FieldRecord.bIsReflected)
		{
			continue;
		}

		SourceBuilder << "\t{ \"" << EscapeString(FieldRecord.Name) << "\", \""
		              << EscapeString(FieldRecord.TypeSpelling) << "\", "
		              << FieldRecord.OffsetBytes << ", "
		              << BuildFlagsInitializer(FieldRecord.PropertyFlags) << ", \""
		              << EscapeString(FieldRecord.Category) << "\" },\n";
	}
	SourceBuilder << "};\n\n";
	SourceBuilder << "struct FRegister_" << InClassRecord.ClassName << "\n";
	SourceBuilder << "{\n";
	SourceBuilder << "\tFRegister_" << InClassRecord.ClassName << "()\n";
	SourceBuilder << "\t{\n";
	SourceBuilder << "\t\tRegisterGeneratedClassReflection(" << InClassRecord.ClassName << "::StaticClass(), GGeneratedProperties_"
	              << InClassRecord.ClassName << ");\n";
	SourceBuilder << "\t}\n";
	SourceBuilder << "};\n\n";
	SourceBuilder << "static FRegister_" << InClassRecord.ClassName << " GRegister_" << InClassRecord.ClassName << ";\n";
	SourceBuilder << "} // namespace\n\n";
	SourceBuilder << "void RegisterGeneratedClass_" << InClassRecord.ClassName << "()\n";
	SourceBuilder << "{\n";
	SourceBuilder << "\tRegisterGeneratedClassReflection(" << InClassRecord.ClassName << "::StaticClass(), GGeneratedProperties_"
	              << InClassRecord.ClassName << ");\n";
	SourceBuilder << "}\n";

	if (!WriteTextFile(GeneratedHeaderPath, HeaderBuilder.str(), OutErrorMessage))
	{
		return false;
	}

	if (!WriteTextFile(GeneratedSourcePath, SourceBuilder.str(), OutErrorMessage))
	{
		return false;
	}

	return true;
}
